###############################################################################
#    ______               __   _
#   / __/ /____ ________ / /  (_)__
#  _\ \/ __/ _ `/ __(_-</ _ \/ / _ \
# /___/\__/\_,_/_/ /___/_//_/_/ .__/
#                            /_/
###############################################################################
                           
###############################################################################
# Global
###############################################################################

command_timeout = 1000
scan_timeout = 30

###############################################################################
# Individual
###############################################################################

[directory]
home_symbol = "ðŸ "
truncation_length = 5

[git_commit]
commit_hash_length = 8
tag_disabled = false

[git_state]
cherry_pick = "ðŸ’"
bisect = "âœ‚ï¸ "

[java]
detect_files = ["pom.xml", "build.xml", "build.gradle", "build.gradle.kts", "project.clj"]
detect_extensions = ["java", "jar", "jsp", "jspf", "class", "clj", "cljs", "cljc"]
